services:
  - type: web
    name: MoodSense
    env: python
    branch: main
    runtime: python-3.11.4
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
